[project]
name = "picogpt"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ameer Arsala <ameer.arsala03@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.9.*"
numpy = ">=2.0.0,<2.1"
regex = ">=2024.5.15,<2024.6"
requests = ">=2.32.3,<2.33"
tqdm = ">=4.66.4,<4.67"
fire = "0.5.0.*"
